### ISSUE TITLE
Missing functions of ReplayMemory class in the replay_memory.py under the sac folder

### ISSUE THREAD

**Issue by yixiaoshenghua** [si0wang/PDML#3]
Dear authors, Your work is fantastic, and I am very interested. However, when I try to reproduce the results by running the codes you provided, I meet the problem listed below, which I think is caused by the missing functions of ReplayMemory class
```
Traceback (most recent call last):
  File "main_pdml.py", line 424, in <module>
    if __name__ == '__main__':
  File "main_pdml.py", line 420, in main

  File "main_pdml.py", line 136, in train
    exploration_before_start(args, env_sampler, env_pool, agent)
AttributeError: 'ReplayMemory' object has no attribute 'update_decay_weights'
```
Could you fix it? Thank you very much!

**Comment by si0wang** [comment]
Sorry for the late reply. You can just remove the import of update_decay_weights.
